os: Visual Studio 2015

environment:
  CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release

configuration:
  - Release

install:

build:

build_script:
  - md build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_THREADING=no ..
  - cmake --build . --config Release
  - cd ..

after_build:
  - cd installer
  - '"%PROGRAMFILES(x86)%\NSIS\makensis" mosquitto.nsi'

artifacts:
  - name: Installer
    path: 'installer/mosquitto-*-install-windows-x86.exe'
  #- path: build\src\Release\mosquitto.exe
  #- path: build\src\Release\mosquitto_passwd.exe
  #- path: build\lib\Release\mosquitto.dll
  #- path: build\lib\Release\mosquitto.lib
  #- path: build\client\Release\mosquitto_pub.exe
  #- path: build\client\Release\mosquitto_sub.exe
  #- path: build\src\Release\mosquitto.exe
