version: '3.7'
networks:
    cs_network:
        external: 'false'
        internal: 'true'
        driver: bridge
        ipam: {}
services:
    ta3_brickell:
        image: ta3_brickell
        build:
            context: ./challenge/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id001
                aliases:
                - challenge_container
        init: true
        environment: &id002
        - HOST=challenge_container
        - PORT=3040
    ta3_brickell_ref_patch:
        image: ta3_brickell
        build:
            context: ./reference_patch/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: *id001
        init: true
        environment: *id002
    ta3_brickell_pov_1:
        image: ta3_brickell_pov_1
        build:
            context: ./pov_1/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id003
                aliases:
                - pov_container
        init: true
        environment: &id004
        - HOST=challenge_container
        - PORT=3040
    ta3_brickell_pov_2:
        image: ta3_brickell_pov_2
        build:
            context: ./pov_2/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id020
                aliases:
                - pov_container
        init: true
        environment: &id030
        - HOST=challenge_container
        - PORT=3040
    ta3_brickell_poller:
        image: ta3_brickell_poller
        build:
            context: ./poller/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id011
                aliases:
                - poller_container
        init: true
        environment: &id012
        - HOST=challenge_container
        - PORT=3040
