version: '3.7'
networks:
    cs_network:
        external: false
        internal: true
        driver: bridge
        ipam: {}
services:
    ta3_grand:
        image: ta3_grand
        build:
            context: ./challenge/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id001
                aliases:
                - challenge_container
        init: true
        environment: &id002
        - HOST=challenge_container
        - PORT=3040
    ta3_grand_ref_patch:
        image: ta3_grand
        build:
            context: ./reference_patch/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: *id001
        init: true
        environment: *id002
    ta3_grand_pov_1:
        image: ta3_grand_pov_1
        build:
            context: ./pov_1/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id003
                aliases:
                - pov_container
        init: true
        environment: &id004
        - HOST=challenge_container
        - PORT=3040
    ta3_grand_pov_2:
        image: ta3_grand_pov_2
        build:
            context: ./pov_2/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id020
                aliases:
                - pov_container
        init: true
        environment: &id030
        - HOST=challenge_container
        - PORT=3040
    ta3_grand_pov_3:
        image: ta3_grand_pov_3
        build:
            context: ./pov_3/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id040
                aliases:
                - pov_container
        init: true
        environment: &id050
        - HOST=challenge_container
        - PORT=3040
    ta3_grand_pov_4:
        image: ta3_grand_pov_4
        build:
            context: ./pov_4/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id060
                aliases:
                - pov_container
        init: true
        environment: &id070
        - HOST=challenge_container
        - PORT=3040
    ta3_grand_pov_5:
        image: ta3_grand_pov_5
        build:
            context: ./pov_5/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id080
                aliases:
                - pov_container
        init: true
        environment: &id090
        - HOST=challenge_container
        - PORT=3040
    ta3_grand_poller:
        image: ta3_grand_poller
        build:
            context: ./poller/
            dockerfile: Dockerfile
            network: host
        security_opt:
        - apparmor:unconfined
        networks:
            cs_network: &id011
                aliases:
                - poller_container
        init: true
        environment: &id012
        - HOST=challenge_container
        - PORT=3040
