name: "Synchronise Coverity Scan branches on a weekly basis"

on:
  workflow_dispatch:
  schedule:
    - cron: "7 3 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git checkout coverity-fixes
          git reset --hard origin/fixes
          git push origin coverity-fixes
          git checkout coverity-develop
          git reset --hard origin/develop
          git push origin coverity-develop
