#ifndef SMB_COMMANDLIST_H
#define SMB_COMMANDLIST_H

//SMB COMMANDS

#define SMB_COM_CREATE_DIRECTORY 0x0
#define SMB_COM_DELETE_DIRECTORY 0x1
#define SMB_COM_OPEN 0x02
#define SMB_COM_CREATE 0x3
#define SMB_COM_CLOSE 0x4
#define SMB_COM_DELETE 0x5
#define SMB_COM_RENAME 0x6
#define SMB_COM_QUERY_INFORMATION 0x7
#define SMB_COM_SET_INFORMATION 0x8
#define SMB_COM_READ 0x9
#define SMB_COM_WRITE 0xa
#define SMB_COM_CREATE_NEW 0xb
#define SMB_COM_NEGOTIATE 0xc
#define SMB_COM_SESSION_SETUP_ANDX 0xd

#endif
