version: '3'
services:
  challenge:
    build: ./challenge/
    volumes:
      - ./challenge:/service
      - ./base_data:/base_data:ro
      - .:/mnt
      - ./data:/data
    ports:
      - 1080
      - 1234
    environment:
      HTTP_PORT: 1080
      ADMIN_PORT: 1234
    working_dir: /service
    command: "make run"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  unpatched:
    build: .
    volumes:
      - ./variants/unpatched:/service
      - ./base_data:/base_data:ro
    ports:
      - 1080
      - 1234
    environment:
      HTTP_PORT: 1080
      ADMIN_PORT: 1234
  fully_patched:
    build: .
    volumes:
      - ./variants/fully_patched:/service
      - ./base_data:/base_data:r0
    ports:
      - 1080
      - 1234
    environment:
      HTTP_PORT: 1080
      ADMIN_PORT: 1234
  poller:
    build: poller
    environment:
      HTTP_PORT: 1080
      ADMIN_PORT: 1234
    volumes:
      - ./poller:/poller
    working_dir: /poller
    command: "python poller.py"
  pov:
    build: pov
    volumes:
      - ./pov:/pov
    ports:
      - 1080
      - 1234
    environment:
      HTTP_PORT: 1080
      ADMIN_PORT: 1234
      URI: "/wiki/cache/Fellowship.html"
